name            'h0tbird-concat'
version         '0.0.1'
source          'https://github.com/h0tbird/puppet-concat'
author          'Marc Villacorta'
license         'GPL'
summary         'Concat Module'
description     'File fragments concatenation.'
project_page    'https://github.com/h0tbird/puppet-concat'
